raw pointer to shared pointer issue
when compiling in ros2 humble with ubuntu 22, the conversion gives the compilation error:

To solve this sharing the ownership of the gh2_future to goal_handle and then to gh2_, as gh2_ is used when canceling the goal.